from typing import Optional
from pydom.types.html.html_element_props import HTMLElementProps


class HTMLInputElement(HTMLElementProps, total=False):
    accept: Optional[str]
    alt: Optional[str]
    auto_complete: Optional[str]
    auto_focus: Optional[str]
    capture: Optional[str]
    checked: Optional[str]
    cross_origin: Optional[str]
    disabled: Optional[bool]
    form: Optional[str]
    form_action: Optional[str]
    form_enctype: Optional[str]
    form_method: Optional[str]
    form_no_validate: Optional[str]
    form_target: Optional[str]
    height: Optional[str]
    list: Optional[str]
    max: Optional[str]
    max_length: Optional[str]
    min: Optional[str]
    min_length: Optional[str]
    multiple: Optional[str]
    name: Optional[str]
    pattern: Optional[str]
    placeholder: Optional[str]
    readonly: Optional[str]
    required: Optional[str]
    selection_direction: Optional[str]
    selection_end: Optional[str]
    selection_start: Optional[str]
    size: Optional[str]
    src: Optional[str]
    step: Optional[str]
    type: Optional[str]
    value: Optional[str]
    width: Optional[str]
