from typing_extensions import TypedDict


class HTMLEventProps(TypedDict, total=False):
    on_abort: str
    on_auto_complete: str
    on_auto_complete_error: str
    on_blur: str
    on_cancel: str
    on_can_play: str
    on_can_play_through: str
    on_change: str
    on_click: str
    on_close: str
    on_context_menu: str
    on_cue_change: str
    on_dbl_click: str
    on_drag: str
    on_drag_end: str
    on_drag_enter: str
    on_drag_leave: str
    on_drag_over: str
    on_drag_start: str
    on_drop: str
    on_duration_change: str
    on_emptied: str
    on_ended: str
    on_error: str
    on_focus: str
    on_input: str
    on_invalid: str
    on_key_down: str
    on_key_press: str
    on_key_up: str
    on_load: str
    on_loaded_data: str
    on_loaded_metadata: str
    on_load_start: str
    on_mouse_down: str
    on_mouse_enter: str
    on_mouse_leave: str
    on_mouse_move: str
    on_mouse_out: str
    on_mouse_over: str
    on_mouse_up: str
    on_mouse_wheel: str
    on_pause: str
    on_play: str
    on_playing: str
    on_progress: str
    on_rate_change: str
    on_reset: str
    on_resize: str
    on_scroll: str
    on_seeked: str
    on_seeking: str
    on_select: str
    on_show: str
    on_sort: str
    on_stalled: str
    on_submit: str
    on_suspend: str
    on_time_update: str
    on_toggle: str
    on_volume_change: str
    on_waiting: str
