name: Publish Python Package

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Bump version
        run: |
          echo "Bumping version..."
          echo "version = \"${{ github.event.release.tag_name }}\"\n" > src/pydom/version.py
          echo "Version bumped to ${{ github.event.release.tag_name }}"

      - name: Commit version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/pydom/version.py
          git commit -m "Bump version to ${{ github.event.release.tag_name }}"
          git push origin HEAD:${{ github.ref_name }} || echo "No changes to commit"

      - name: Build package
        run: python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
